### ISSUE TITLE
Workflows don't work 

### ISSUE THREAD

**Issue by angelo24782** [zero-to-mastery/Animation-Nation#963] opened 2020-11-13 09:27 UTC
It doesn't work anymore something has broken, on .github / workflows / format-code.yml.

Syntax errors are reported to be corrected on various projects. @sophiabrandt

**Comment by sophiabrandt** [comment] 2020-11-13 10:18
The workflow works exactly as intended. It will throw errors when there are files that don't conform to the prettier spec. It's mostly incorrect HTML syntax.
The reason is that the workflow won't run a new deploy until all errors are fixed.

The workflow shows the errors when you click on the "Actions tab".

Currently, a few other ZTM members have committed broken HTML, so no deployments will happen.

I will fix the errors manually and push a new commit.

**Comment by sophiabrandt** [comment] 2020-11-13 10:26
Fixed with #964.
Steps I took:
```sh
npx prettier -w -u .
```
This will run prettier on all files. Then I manually corrected the files that threw errors.

**Closed by sophiabrandt** 2020-11-13 10:26 UTC

**Comment by angelo24782** [comment] 2020-11-13 10:32
Excuse me @sophiabrandt  but because the site animation-nation.netlify.app/ doesn't work anymore :-(

**Comment by sophiabrandt** [comment] 2020-11-13 13:34
Netlify Builds are disabled at the moment, because they were triggered too often during Hacktoberfest. Matt will trigger a manual build with Netlify.
I don't have access to the Netlify repo.
