### ISSUE TITLE
Link Not Displaying the Content .....

### ISSUE THREAD

**Issue by PrasadM07** [zero-to-mastery/Animation-Nation#599] opened 2020-06-15 06:08 UTC

**Comment by sophiabrandt** [comment] 2020-06-30 05:44
This seems to be a duplicate of https://github.com/zero-to-mastery/Animation-Nation/issues/442.
I will close this. If you feel that it's not a duplicate, please provide further information, and I will looki into it.

**Closed by sophiabrandt** 2020-06-30 05:44 UTC
